### ISSUE TITLE
server name not saving, always reverts to "iPhone"

### ISSUE THREAD

**Issue by luckman212** [neon443/AirAP#2]
This is a neat project! I've been using [SonoBus](https://sonobus.net/) for this, but this is much simpler!

One thing I noticed is, every time I close and reopen the app, the "server" name has reverted back to the default "iPhone"

Other settings such as background and metadata are saving/loading correctly.

Tested on 2.7.1 (1), iPhone 16 Pro / iOS 18.5

**Comment by luckman212** [comment]
Maybe this is the problem area?

https://github.com/neon443/AirAP/blob/eb548a5d127342b273d2b97f2a0f5c6272e29b7e/AirAP/AirstreamManager.swift#L24

In any case, would `UIDevice.current.name` be more suitable? It would return a more specific token like "Mike's iPhone" instead of just "iPhone"

**Comment by neon443** [comment]
Done:
  It now uses UIDevice.current.name, and remembers what you chose
Pushed to AppStore connect!

**Comment by luckman212** [comment]
Cool 👍 I will watch for it to appear on TestFlight. So far not yet

**Comment by luckman212** [comment]
I got version 2.8.4 (3) now but it still doesn't save the server name, it always reverts to "iPhone".

**Comment by luckman212** [comment]
Cool I will check! Hasn't hit my Testflight yet. I'm not on iOS 26 -- personally I hate the liquid (gl)ass design but maybe they will tone it down a bit before release.

**Comment by neon443** [comment]
No problem!
It's still "in review" 💀

**Comment by neon443** [comment]
It's out now!
